### ISSUE TITLE
Enhancement: Line up bottom of unit of measure and value

### ISSUE THREAD

**Issue by hannav95** [PredixDev/px-kpi#6]
## Expected behavior and actual behavior:
Would like there to be more padding between KPI title and value, so unit of measure and value will have the same baseline.

## Screenshots (_optional, but very helpful_):
Actual: 
![image](https://user-images.githubusercontent.com/12763767/33040771-16812d38-ce0a-11e7-8fcc-5f62e800cbce.png)

Request: 
![image](https://user-images.githubusercontent.com/12763767/33040738-fb2ff32a-ce09-11e7-8c80-248d0e5bf675.png)

**Comment by randyaskin** [comment]
Hi @hannav95 - are you customizing/overriding any variables or constraining the space around the KPI in some way? The component's default state looks more like your Requested picture than the Actual one. Can you also confirm that the proper font is being loaded? It looks like Inspira Sans, but just want to double check, because the positioning of this component is unfortunately based heavily on the baseline of the font in use.

From the demo page:
![screen shot 2017-12-20 at 12 24 20 pm](https://user-images.githubusercontent.com/2130613/34227184-200737e2-e581-11e7-85b8-8520378db74b.png)

**Comment by hannav95** [comment]
@randyaskin I use the KPI within a px-card and only add a padding to the top and margin the left. I still see what I have in the actual image even with those styles removed. The font family is set to `GE Inspira Sans,Helvetica,Arial,sans-serif`.
